variable "apes_backend_bucket" {}
variable "elemental_archive_input_bucket" {}
variable "medialive_input_sg_cidr" {}
variable "medialive-stack_name" {}
variable "medialive_input_name" {}
variable "medialive_input_codec" {}
variable "medialive_input_maximum_bitrate" {}
variable "medialive_input_resolution" {}
variable "media_access_role_arn" {}
variable "input_destination_a" {}
variable "input_destination_b" {}
variable "mediapackage_destination_id" {}
variable "mediapackage_channel_id" {}
variable "medialive_channel_name" {}
variable "medialive_outputgroup_name" {}
variable "medialive_outputgroup_destination_id" {}
variable "medialive_output_name" {}
variable "videodescription_name" {}
# Variables related to Video Description
variable "videodescription_framerate_control" {}
variable "videodescription_par_control" {}
variable "videodescription_framerate_denominator" {}
variable "videodescription_framerate_numerator" {}
variable "videodescription_adaptive_quantization" {}
variable "videodescription_afd_signaling" {}
variable "videodescription_bitrate" {}
variable "videodescription_color_metadata" {}
variable "videodescription_entropy_encoding" {}
variable "videodescription_flicker_aq" {}
variable "videodescription_gop_b_reference" {}
variable "videodescription_gop_closed_cadence" {}
variable "videodescription_gop_numb_frames" {}
variable "videodescription_gop_size" {}
variable "videodescription_gop_size_units" {}
variable "videodescription_level" {}
variable "videodescription_look_ahead_rate_control" {}
variable "videodescription_num_ref_frames" {}
variable "videodescription_par_denominator" {}
variable "videodescription_par_numerator" {}
variable "videodescription_profile" {}
variable "videodescription_rate_control_mode" {}
variable "videodescription_scene_change_detect" {}
variable "videodescription_slices" {}
variable "videodescription_spatial_aq" {}
variable "videodescription_syntax" {}
variable "videodescription_temporal_aq" {}
variable "videodescription_timecode_insertion" {}
variable "videodescription_height" {}
variable "videodescription_width" {}
variable "medialive_archive_output_group_name" {}
variable "medialive_archive_output_name" {}
variable "medialive_archive_destination_id" {}
#variable "medialive_archive_destination_url" {}
variable "m2ts_absent_input_audiobehavior" {}
variable "m2ts_arib" {}
variable "m2ts_arib_captions_pid" {}
variable "m2ts_arib_captions_pid_control" {}
variable "m2ts_audio_buffer_model" {}
variable "m2ts_audio_frames_per_pes" {}
variable "m2ts_audio_pids" {}
variable "m2ts_audio_stream_type" {}
variable "m2ts_buffer_model" {}
variable "m2ts_cc_descriptor" {}
variable "m2ts_dvb_sub_pids" {}
variable "m2ts_dvb_teletext_pid" {}
variable "m2ts_ebif" {}
variable "m2ts_ebp_audio_interval" {}
variable "m2ts_ebp_placement" {}
variable "m2ts_es_rate_in_pes" {}
variable "m2ts_etv_platform_pid" {}
variable "m2ts_etv_signal_pid" {}
variable "m2ts_klv" {}
variable "m2ts_klv_data_pids" {}
variable "m2ts_nielsen_id3_behavior" {}
variable "m2ts_pat_interval" {}
variable "m2ts_pcr_control" {}
variable "m2ts_pcr_period" {}
variable "m2ts_pmt_interval" {}
variable "m2ts_pmt_pid" {}
variable "m2ts_rate_mode" {}
variable "m2ts_scte27_pids" {}
variable "m2ts_scte35_control" {}
variable "m2ts_scte35_pid" {}
variable "m2ts_segmentation_markers" {}
variable "m2ts_segmentation_style" {}
variable "m2ts_timed_metadata_behavior" {}
variable "m2ts_timed_metadata_pid" {}
variable "m2ts_video_pid" {}
# Variables related to Audio Description
variable "audiodescriptions_audio_selector_name" {}
variable "audiodescriptions_audio_type_control" {}
variable "audiodescriptions_language_code_control" {}
variable "audiodescriptions_name" {}
variable "aacsettings_bitrate" {}
variable "aacsettings_coding_mode" {}
variable "aacsettings_input_type" {}
variable "aacsettings_profile" {}
variable "aacsettings_rate_control_mode" {}
variable "aacsettings_raw_format" {}
variable "aacsettings_sample_rate" {}
variable "aacsettings_spec" {}
variable "tags"             {}

#variable "medialive_stream_name" {}